### ISSUE TITLE
error in nuxt3

### ISSUE THREAD

**Issue by kimsourly** [wobsoriano/vue-use-places-autocomplete#2]
Named export 'Loader' not found. The requested module '@googlemaps/js-api-loader' is a CommonJS module, which may not support all module.exports as named exports. CommonJS modules can always be imported via the default export, for example using: import pkg from '@googlemaps/js-api-loader'; const { Loader } = pkg;

**Comment by wobsoriano** [comment]
Try to add it to `build.transpile` of your nuxt config

**Comment by wobsoriano** [comment]
Feel free to reopen
