### ISSUE TITLE
Is it possible to grab placeDetails from query'ed result

### ISSUE THREAD

**Issue by cxammar** [wobsoriano/vue-use-places-autocomplete#3]
Hi, 

Many thanks for building this package, it's very useful. I'm trying to fetch the placeDetails of a placeid i'm getting from your code but I'm finding it impossible to do. Any suggestions ? Thanks!!

**Comment by cxammar** [comment]
I got it ! Thanks anyways and thanks for your work!!

**Comment by wobsoriano** [comment]
Appreciate. Thanks!
