### ISSUE TITLE
Options API

### ISSUE THREAD

**Issue by pedroAlba** [wobsoriano/vue-use-places-autocomplete#4]
Hi!

Any tips on using this on a component that uses the traditional Options API? I'm having a hard time setting up in my project, specially when setting the "watcher" property.

`Invalid watch source:   A watch source can only be a getter/effect function, a ref, a reactive object, or an array of these types. `

Thanks

**Comment by ridvansumset** [comment]
`setup` and `methods` of an Options API component:
```js
setup() {
    const locationQuery = ref('')

    const { suggestions, loading } = usePlacesAutocomplete(locationQuery, {
      apiOptions: {
        language: 'en'
      },
      autocompletionRequest: {
        types: ['(cities)']
      },
      debounce: 500,
      minLengthAutocomplete: 3,
      apiKey: 'YOUR_API_KEY'
    })

    return { locationQuery, suggestions, loading }
  },
  methods: {
    onLocationSearch(query: string) {
      this.locationQuery = query
    }
  }
```
if you have an input element in the template that triggers `onLocationSearch` and a list element to display `suggestions` with `v-for` you're good to go.

**Comment by wobsoriano** [comment]
~~Hi sorry but support for Options API is not planned.~~

Here ya go - https://github.com/wobsoriano/vue-use-places-autocomplete/pull/8
