### ISSUE TITLE
How to return the address types?

### ISSUE THREAD

**Issue by bdlowery** [wobsoriano/vue-use-places-autocomplete#5]
Is it possible to get the `address_components` Array from the selected suggestions this package returns? - https://developers.google.com/maps/documentation/javascript/reference/places-service#PlaceResult.address_components

It gives access to things like:
```
[
   long_name: 'California',
   short_name: 'CA',
   types: ['state']
],
[
   long_name: '12408',
   short_name: '12408',
   types: ['street_number']
]
```

Getting the types for each query would be super helpful as it can be used to programmatically autocomplete other inputs in the form.

For example, if the address is `1234 College Court, Sacramento, CA", the address components would be:
```
[
   long_name: 'California',
   short_name: 'CA',
   types: ['state']
],
[
   long_name: 'Sacramento',
   short_name: 'Sacramento',
   types: ['locality']
],
[
   long_name: '1234',
   short_name: '1234',
   types: ['street_number']
],
[
   long_name: 'College Court',
   short_name: 'College Court',
   types: ['route']
]
```
Allowing me to programatically select each different type and put them into the correct input fields.

As of right now the `suggestions` array returned by the package doesn't give any information about which part of the address is which

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/vue-use-places-autocomplete/issues/7
