### ISSUE TITLE
How to access address components ?

### ISSUE THREAD

**Issue by lewebsimple** [wobsoriano/vue-use-places-autocomplete#7]
Is there a way to access the address components from the returned suggestions (i.e. postal code, city, etc) ?

**Comment by wobsoriano** [comment]
Hi! Please update to latest version, and try `geocodeByPlaceId`:

```ts
import { geocodeByPlaceId } from 'vue-use-places-autocomplete'

geocodeByPlaceId('PLACE_ID')
```

and look inside`address_components` of item 0.

Feel free to reopen!
